In [32]:
import numpy as np
import random

class grid:
    
    GENERATOR = [-1, 1]

    def __init__(self, n):
        self.n = n
        # горизонтальные
        self.horisontal = self.fill(n, n-1)
        # вертикальные
        self.vertical = self.fill(n-1, n)
        # узлы
        self.vertex = self.fill(n, n)
        # для суммы
        #self.energy_in_vertex = np.zeros((n, n))
        print(self.vertex)
        print(self.horisontal)
        print(self.vertical)
    
    def fill(self, n, m):
        res = np.zeros((n, m))
        for i in range(n):
            for j in range(m):
                res[i][j] = self.GENERATOR[random.randint(0, 1)]
        return res
#энергия в вершинах:    
#self.energy_in_vertex[i, j] = vertex[i-1, j] * vertex[i, j] * vertical[i-1, j] + vertex[i+1, j] * vertex[i, j] * vertical[i, j] + vertex[i, j-1] * vertex[i, j] * horisontal[i, j-1] + vertex[i, j+1] * vertex[i, j] * horisontal[i, j]
#total energy:
# for i in range(n):
#     for i in range(n):
#         H(vertex) += -(energy_in_vertex[i,j])
#H зависит от того, какие значение в вершинах.
grid(4)

[[ 1. -1.  1.  1.]
 [ 1.  1.  1.  1.]
 [-1.  1. -1.  1.]
 [ 1. -1.  1. -1.]]
[[-1.  1. -1.]
 [-1. -1.  1.]
 [-1.  1.  1.]
 [ 1. -1.  1.]]
[[ 1.  1. -1.  1.]
 [ 1.  1. -1. -1.]
 [-1.  1. -1.  1.]]


In [25]:
print(horisontal)

NameError: name 'horisontal' is not defined